### ISSUE TITLE
Get rosters data (link between name and handle name)

### ISSUE THREAD

**Issue by yves-chevallier** [education/classroom#2403]
I love the idea of GitHub Classroom, but it is currently a bit cumbersome for me to do the assignments correction. When I use the Classroom Assistant, it syncs the repositories with some limitations: 

- The destination repository is named using the student's handle name, not the real student name. Some of my student already have a GitHub account such as "Darth Vader" and it is hard for me to link both names. 
- It lacks meta-data. I would love to have a local file with such content: 

```yaml
# Meta data related to GitHub Classroom
---
assignment:
  name: First Assignment
  date: 2019-09-12    
roster:
  darth-vader:
    name: John Doe
    commit: 948a7c4b5d6f5e4a5f6e4ca5 # Last commit before the deadline
    date: 2019-09-13T12:22:41 # Submission date
```

My goal is to easily get the following information to automate the assignment correction

- Link between GitHub handle and student name
- Value of the last commit
